//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CG2019112315.rc 使用
//
#define IDD_INPUT_DIALOG1               9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CG2019112315GDI2DTYPE       130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_DRAW_CDC                     139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_PEN_COLOR                    141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_CG2019112315GDI3DTYPE       310
#define IDR_CG2019112315OGL3DTYPE       311
#define IDC_EDIT1                       1000
#define IDC_INPUT_VALUE1                1000
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_PEN_WIDTH                    32772
#define ID_PEN_STYLE                    32774
#define ID_BRUSH_USE                    32775
#define ID_BRUSH_COLOR                  32776
#define ID_BRUSH_INDEX                  32777
#define ID_ALGORITHM_LINE               32783
#define ID_ALGORITHM_POLYGON            32785
#define ID_ALGORITHM_CIRCLE             32786
#define ID_POINTER                      32787
#define ID_DRAW_POINT                   32788
#define ID_BUTTON4                      32789
#define ID_DRAW_LINESEG                 32790
#define ID_DRAW_LINE                    32791
#define ID_DRAW_RAY                     32792
#define ID_DRAW_BROKEN_LINE             32793
#define ID_BUTTON9                      32794
#define ID_DRAW_BSPLINE                 32795
#define ID_DRAW_CIRCLE_1POINT_RADIUS    32796
#define ID_DRAW_CIRCLE_2POINT_DIAMETER  32798
#define ID_DRAW_CIRCLE_3POINT           32799
#define ID_DRAW_ARC_3POINT              32800
#define ID_DRAW_FAN_3POINT              32801
#define ID_DRAW_SEMICIRCLE_2POINT       32802
#define ID_DRAW_CIRCUM_ARC              32803
#define ID_DRAW_CIRCUM_FAN              32804
#define ID_DRAW_ELLIPSE                 32805
#define ID_DRAW_ELLIPSE_ARC             32806
#define ID_DRAW_ELLIPSE_FAN             32807
#define ID_DRAW_POLYGON                 32808
#define ID_DRAW_POLYGUN_REGUALR         32809
#define ID_DRAW_POLYGON_SIDE            32810
#define ID_DRAW_TRACE                   32811
#define ID_DRAW_BEZIER                  32812
#define ID_DRAW_CIRCLE_2POINT_RADIUS    32813
#define ID_ALGORITHM_SEED               32814
#define ID_BOUND_COLOR                  32815
#define ID_INNER_COLOR                  32816
#define ID_PICK_ALL                     32817
#define ID_PICK_NONE                    32818
#define ID_PICK_ONE                     32819
#define ID_PICK_SEED_POINT              32820
#define ID_DRAW_2DLINE_TIME             32822
#define ID_TRANSFORM_TRANSLATE_RIGHT    32823
#define ID_TRANSFORM_TRANSLATE_UP       32824
#define ID_TRANSFORM_TRANSLATE_DOWN     32826
#define ID_TRANSFORM_TRANSLATE_FRONT    32827
#define ID_TRANSFORM_TRANSLATE_BACK     32828
#define ID_TRANSFORM_TRANSLATE_FREE     32829
#define ID_TRANSFORM_ROTATE_ORIGIN      32830
#define ID_TRANSFORM_ROTATE_PICK_POINT  32831
#define ID_TRANSFORM_SCALE_UP           32832
#define ID_TRANSFORM_SCALE_DOWN         32833
#define ID_TRANSFORM_SCALE              32834
#define ID_TRANSFORM_MIRROR_X_AXIS      32835
#define ID_TRANSFORM_MIRROR_Y_AXIS      32836
#define ID_TRANSFORM_MIRROR_ORIGIN      32837
#define ID_TRANSFORM_MIRROR_Y_EQ_POS_X  32838
#define ID_TRANSFORM_MIRROR_Y_EQ_NEG_POS_X 32839
#define ID_TRANSFORM_MIRROR_CHOOSE_LINE 32840
#define ID_TRANSFORM_SHEAR_X_AXIS       32841
#define ID_TRANSFORM_SHEAR_Y_AXIS       32842
#define ID_TRANSFORM_SHEAR_X_Y_AXIS     32843
#define ID_TRANSFORM_MATRIX             32844
#define ID_BUTTON24                     32845
#define ID_TRANSFORM_TRANSLATE_LEFT     32846
#define ID_MOVE_VIEWPOINT               32847
#define ID_EXTEND_VIEW                  32848
#define ID_NARROW_VIEW                  32849
#define ID_ROTATE_VIEW                  32850
#define ID_SHOW_ALL                     32851
#define ID_SELECT_VIEW                  32852
#define ID_BUTTON8                      32853
#define ID_RESET_CAMERA                 32853

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         32854
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
